### ISSUE TITLE
documentation for the settings.json

### ISSUE THREAD

**Issue by ed-jaeger** [danwhitfield/sparql-executor-vscode-extension#12]
I was wondering if there was any documentation to the format for settings.json.  In particular, I was wondering how to query against a local 'ttl' file.

**Comment by danwhitfield** [comment]
Hi @ed-jaeger, sorry but I’m not sure how querying a local TTL file directly would work without some kind of SPARQL server (e.g. Blazegraph) to parse abs serve the file.
