### ISSUE TITLE
Table vs JSON output

### ISSUE THREAD

**Issue by ktk** [danwhitfield/sparql-executor-vscode-extension#18]
First, thanks for the extension, looks useful! I got some questions regarding the result handling:

- why JSON as default output? SPARQL SELECT is row-oriented and I don't see why I would want to get JSON by default, that's not practically for working on a query.
- can I override JSON globally instead of doing it for each endpoint?
- The good thing about the JSON output is that it shows up in the "output" tab. Getting a new tab with a table is not very handy for quick interactions on a query. Could this be done with table output as well?

thanks!

**Comment by danwhitfield** [comment]
Hi, thanks for your feedback.

> why JSON as default output? SPARQL SELECT is row-oriented and I don't see why I would want to get JSON by default, that's not practically for working on a query.

I built this initially because I _did_ want the output as JSON. I made sure there there was also a table format.

> can I override JSON globally instead of doing it for each endpoint?

Not currently.

> The good thing about the JSON output is that it shows up in the "output" tab. Getting a new tab with a table is not very handy for quick interactions on a query. Could this be done with table output as well?

Not unless there's huge demand for it and I find time to build it.

Glad you like the extension.
