### ISSUE TITLE
No SPARQL endpoints configured

### ISSUE THREAD

**Issue by moldach** [danwhitfield/sparql-executor-vscode-extension#20]
After opening `settings.json` via `CMD + Shift + P` and replacing with the example:

```
"sparql-executor.endpoints": [
       {
         "protocol": "https",
         "host": "query.wikidata.org",
         "path": "/sparql",
         "name": "Wikidata",
         "customHeaders": [
           {
             "headerName": "User-Agent",
             "headerValue": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
           },
         ],
         "method": "GET",
         "queryParameterName": "query"
       },
       {
         "protocol": "https",
         "host": "dbpedia.org",
         "name": "DBpedia",
         "path": "/sparql"
       }
]
```

I save the file then try to Select SPARQL Endpoint Using Command Palette:

* `cmd` + `shift` + `P`
* Type the command Select SPARQL Endpoint
* Hit enter

Here I see an error in the bottom right corner of VS Studio saying:

> No SPARQL endpoints configured.

Do you know what the issue is here?

**Comment by danwhitfield** [comment]
Hi @moldach,

I just tested with your exact SPARQL endpoints settings JSON and the good news is that it worked perfectly.

<img width="1040" alt="Screen Shot 2021-11-05 at 7 08 20 AM" src="https://user-images.githubusercontent.com/368236/140395779-d19e9645-753d-447a-840a-fd43d6beee96.png">
<img width="1096" alt="Screen Shot 2021-11-05 at 7 08 31 AM" src="https://user-images.githubusercontent.com/368236/140395789-877b97b3-9651-404b-a7fe-9a61931122f5.png">
<img width="964" alt="Screen Shot 2021-11-05 at 7 08 52 AM" src="https://user-images.githubusercontent.com/368236/140395793-db67ecbe-ddd5-4a12-b4e1-78f4df6cb49c.png">

I suspect that you perhaps didn't correctly set the SPARQL endpoint you desired. This part of your steps to replicate:

> - cmd + shift + P
> - Type the command Select SPARQL Endpoint
> - Hit enter

makes me think that you just hit enter on the 'Select SPARL Endpoint' option, but didn't select the actual endpoint. After hitting enter on 'Select SPARQL Endpoint' you should see a list of endpoints to choose from, like this:

<img width="678" alt="Screen Shot 2021-11-05 at 7 09 33 AM" src="https://user-images.githubusercontent.com/368236/140396160-e70d1090-ee1b-4cb5-89ca-811509546ddd.png">

You then must select either 'Wikidata' or 'DBpedia'. 

Thanks,
Dan

**Comment by moldach** [comment]
Hi Dan,

The problem is that after hitting enter on 'Select SPARQL Endpoint' is that it does not show those options in the drop down.

It immediately goes to the error in the bottom right corner
